/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resources: Resource;
    'field-translations': FieldTranslation;
    projects: Project;
    'pre-resources': PreResource;
    'api-keys': ApiKey;
    conversations: Conversation;
    messages: Message;
    subscriptions: Subscription;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    projects: {
      videos: 'resources';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'field-translations': FieldTranslationsSelect<false> | FieldTranslationsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'pre-resources': PreResourcesSelect<false> | PreResourcesSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    configuracion: Configuracion;
  };
  globalsSelect: {
    configuracion: ConfiguracionSelect<false> | ConfiguracionSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Empresa o organización a la que pertenece el usuario
   */
  empresa?: string | null;
  /**
   * Rol del usuario para control de acceso
   */
  role?: ('admin' | 'user' | 'api') | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility
   */
  alt: string;
  /**
   * Display title for the media file
   */
  title?: string | null;
  /**
   * Optional description of the media content
   */
  description?: string | null;
  /**
   * Type of media content
   */
  mediaType?: ('document' | 'image') | null;
  /**
   * Number of pages (for PDF documents)
   */
  pages?: number | null;
  /**
   * Tags for organizing and searching documents and images
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  /**
   * Título descriptivo del recurso
   */
  title: string;
  /**
   * Proyecto al que pertenece este recurso (para organización temática)
   */
  project: string | Project;
  /**
   * Namespace para organizar contenidos (ej: curso-matematicas, empresa-acme)
   */
  namespace: string;
  /**
   * Campo gestionado automáticamente por el sistema al guardar
   */
  lastUpdatedBy?: (string | null) | User;
  nombre_cliente?: string | null;
  /**
   * Selecciona el tipo de caso para mostrar los campos correspondientes
   */
  caso?:
    | (
        | 'factura_suministros'
        | 'desplazamientos'
        | 'materias_primas'
        | 'viajes_tipo_2'
        | 'variado_emails'
        | 'consumos_combustible_tipo_1'
        | 'residuos'
        | 'viajes_tipo_1'
        | 'otros'
      )
    | null;
  tipo?:
    | (
        | 'electricidad'
        | 'agua'
        | 'gas'
        | 'combustible'
        | 'gasolinera'
        | 'taxi_vtc'
        | 'prebuilt-invoice'
        | 'prebuilt-receipt'
        | 'otros'
      )
    | null;
  factura_suministros?: {
    codigo_suministro?: string | null;
    periodo_consumo?: {
      fecha_inicio?: string | null;
      fecha_fin?: string | null;
    };
    fecha_compra?: string | null;
    volumen_consumido?: number | null;
    unidad_medida?: ('kWh' | 'L' | 'm3' | 'kg' | 'km') | null;
    proveedor_servicio?: string | null;
    codigo_factura?: string | null;
  };
  desplazamientos?: {
    fecha_servicio?: string | null;
    empresa_servicio?: ('uber' | 'cabify' | 'taxi' | 'bolt' | 'otra') | null;
    importe?: number | null;
    moneda?: ('EUR' | 'USD' | 'GBP') | null;
    cantidad_consumida?: number | null;
    unidad_medida?: ('km' | 'L') | null;
    tipo_combustible?: ('gasolina' | 'diesel' | 'GLP' | 'NA') | null;
    codigo_factura?: string | null;
  };
  materias_primas?: {
    nombre_proveedor?: string | null;
    fecha_factura?: string | null;
    codigo_factura?: string | null;
    tipo_producto?: string | null;
    descripcion_producto?: string | null;
    peso_kg?: number | null;
    importe?: number | null;
    moneda?: ('EUR' | 'USD' | 'GBP') | null;
  };
  viajes_tipo_2?: {
    fecha_viaje?: string | null;
    medio_transporte?: ('avion' | 'tren' | 'ferry' | 'coche') | null;
    origen?: string | null;
    destino?: string | null;
    escalas?:
      | {
          escala?: string | null;
          id?: string | null;
        }[]
      | null;
    numero_personas?: number | null;
    categoria_billete?: ('turista' | 'preferente' | 'business' | 'primera') | null;
    tipo_trayecto?: ('ida' | 'ida_vuelta') | null;
    distancia?: number | null;
    fuente_distancia?: string | null;
    codigo_factura?: string | null;
  };
  variado_emails?: {
    remitente?: string | null;
    fecha?: string | null;
    descripcion_consumo?: string | null;
    cantidad?: number | null;
    unidad_medida?: ('kWh' | 'L' | 'm3' | 'kg' | 'km' | 'ud') | null;
  };
  consumos_combustible_tipo_1?: {
    codigo_tarjeta_o_matricula?: string | null;
    fecha_repostaje?: string | null;
    cantidad_combustible?: number | null;
    unidad_medida?: ('L' | 'kg' | 'kWh') | null;
    tipo_combustible?: ('gasolina' | 'diesel' | 'GLP') | null;
    importe?: number | null;
    moneda?: ('EUR' | 'USD' | 'GBP') | null;
    codigo_factura?: string | null;
  };
  residuos?: {
    codigo_recogida?: string | null;
    localizacion_recogida?: string | null;
    fecha_recogida?: string | null;
    tipo_residuo?: ('papel' | 'plastico' | 'organico' | 'vidrio' | 'mixto' | 'peligroso' | 'otro') | null;
    cantidad_residuo?: number | null;
    unidad_medida?: ('kg' | 't') | null;
  };
  viajes_tipo_1?: {
    fecha_viaje?: string | null;
    medio_transporte?: ('avion' | 'tren' | 'ferry' | 'coche') | null;
    origen?: string | null;
    destino?: string | null;
    escalas?:
      | {
          escala?: string | null;
          id?: string | null;
        }[]
      | null;
    numero_personas?: number | null;
    categoria_billete?: ('turista' | 'preferente' | 'business' | 'primera') | null;
    tipo_trayecto?: ('ida' | 'ida_vuelta') | null;
    distancia?: number | null;
    fuente_distancia?: string | null;
    codigo_factura?: string | null;
  };
  /**
   * Filtros JSON para configuración de Pinecone (opcional)
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Metadatos JSON del usuario para identificación en webhooks (opcional)
   */
  user_metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Texto extraído del documento (auto-generado)
   */
  extractedText?: string | null;
  /**
   * Descripción general del documento generada por IA (auto-generado)
   */
  description?: string | null;
  /**
   * Páginas del documento con contenido extraído (auto-generado)
   */
  documentPages?:
    | {
        /**
         * Número de página
         */
        pageNumber: number;
        /**
         * Texto extraído de esta página
         */
        extractedText: string;
        /**
         * Resumen del contenido de la página generado por IA
         */
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Segmentos de texto del documento para generar embeddings (auto-generado)
   */
  chunks?:
    | {
        /**
         * Índice del segmento de texto
         */
        chunkIndex: number;
        /**
         * Número de página de origen (para PDFs)
         */
        pageNumber?: number | null;
        /**
         * Contenido de texto del segmento
         */
        content: string;
        /**
         * Resumen del contenido generado por IA
         */
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tipo de recurso a procesar
   */
  type: 'document' | 'image';
  /**
   * Archivo multimedia subido
   */
  file: string | Media;
  /**
   * Estado actual del procesamiento
   */
  status: 'pending' | 'uploading' | 'processing' | 'completed' | 'failed' | 'needs_review';
  /**
   * Progreso del procesamiento (0-100%)
   */
  progress?: number | null;
  /**
   * Logs detallados del proceso de ingesta
   */
  logs?:
    | {
        /**
         * Nombre del paso (ej: transcribe, scenes, embedding)
         */
        step: string;
        status: 'started' | 'progress' | 'success' | 'error';
        at: string;
        /**
         * Detalles adicionales del paso
         */
        details?: string | null;
        /**
         * Datos específicos del paso (JSON)
         */
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Resultado de Azure Document Intelligence recibido via webhook
   */
  analyzeResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Estado de confianza del documento basado en la calidad de los campos analizados
   */
  confidence?: ('empty' | 'needs_revision' | 'trusted' | 'verified') | null;
  /**
   * Metadatos del procesamiento
   */
  processingMetadata?: {
    /**
     * Número de páginas del documento
     */
    pages?: number | null;
    /**
     * Número de segmentos de texto generados
     */
    textChunks?: number | null;
    /**
     * Número de vectores creados en Pinecone
     */
    vectorsGenerated?: number | null;
    /**
     * IDs de jobs en el sistema de cola
     */
    jobIds?:
      | {
          jobId?: string | null;
          type?: ('document-processing' | 'embedding-generation') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * URL de webhook para notificaciones específicas de este recurso
   */
  webhookUrl?: string | null;
  /**
   * Secret para validar webhooks
   */
  webhookSecret?: string | null;
  /**
   * Identificador del usuario o sistema que subió el recurso
   */
  uploadedBy?: string | null;
  /**
   * Origen o contexto del recurso
   */
  source?: string | null;
  /**
   * Momento en que comenzó el procesamiento
   */
  startedAt?: string | null;
  /**
   * Momento en que completó el procesamiento
   */
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona proyectos para organizar vídeos temáticamente
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Título descriptivo del proyecto (único por usuario)
   */
  title: string;
  /**
   * URL amigable autogenerada desde el título (único globalmente)
   */
  slug: string;
  /**
   * Descripción detallada del proyecto (opcional)
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videos?: {
    docs?: (string | Resource)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Usuario que creó el proyecto
   */
  createdBy: string | User;
  /**
   * Fecha de creación del proyecto
   */
  createdAt: string;
  /**
   * Fecha de última actualización
   */
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-translations".
 */
export interface FieldTranslation {
  id: string;
  key: string;
  /**
   * Orden ascendente para mostrar campos
   */
  order?: number | null;
  label: string;
  /**
   * Indica si el campo es obligatorio
   */
  isRequired?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registros temporales de documentos multi‑factura para división (solo admin).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pre-resources".
 */
export interface PreResource {
  id: string;
  /**
   * Proyecto destino para los resources derivados
   */
  project: string | Project;
  /**
   * Logs del proceso Splitter para diagnóstico
   */
  logs?:
    | {
        step: string;
        status: 'started' | 'progress' | 'success' | 'error';
        at: string;
        details?: string | null;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Usuario que inició el proceso
   */
  user: string | User;
  /**
   * Archivo PDF original subido
   */
  file: string | Media;
  /**
   * Estado de procesamiento del pre‑resource
   */
  status: 'pending' | 'processing' | 'splitting' | 'error' | 'done';
  /**
   * Respuesta del Splitter utilizada para dividir el PDF
   */
  splitterResponse?: {
    /**
     * Índices 1‑based de primeras páginas de cada factura
     */
    pages?:
      | {
          page: number;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Mensaje de error (si falla endpoint o validación de pages)
   */
  error?: string | null;
  /**
   * IDs de resources creados a partir de este pre‑resource
   */
  derivedResourceIds?:
    | {
        resourceId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Gestionado automáticamente por el sistema
   */
  lastUpdatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestiona API Keys para acceso externo a proyectos de usuario
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: string;
  /**
   * Nombre descriptivo de la API Key (único por usuario)
   */
  name: string;
  /**
   * Valor de la API Key (generado automáticamente)
   */
  keyValue: string;
  /**
   * Últimos 4 caracteres de la API Key (para mostrar)
   */
  keyValueLastFour: string;
  /**
   * Usuario propietario de la API Key
   */
  user: string | User;
  /**
   * Proyectos específicos con acceso (vacío si hasAllProjects es true)
   */
  projects?: (string | Project)[] | null;
  /**
   * Si esta key tiene acceso a todos los proyectos del usuario
   */
  hasAllProjects?: boolean | null;
  /**
   * Marca esta API Key como la clave automática para el chatbot de playground
   */
  playgroundKey?: boolean | null;
  /**
   * Fecha de creación de la API Key
   */
  createdAt: string;
  /**
   * Fecha de última actualización
   */
  updatedAt: string;
}
/**
 * Conversaciones del chat IA con los usuarios
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  /**
   * Título descriptivo de la conversación (generado automáticamente o personalizado)
   */
  title: string;
  /**
   * Usuario propietario de esta conversación
   */
  user: string | User;
  /**
   * Indica si la conversación está activa o archivada
   */
  isActive?: boolean | null;
  /**
   * Contador de mensajes en esta conversación (actualizado automáticamente)
   */
  messageCount?: number | null;
  /**
   * Fecha del último mensaje en esta conversación
   */
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes individuales de las conversaciones del chat IA
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  /**
   * Conversación a la que pertenece este mensaje
   */
  conversation: string | Conversation;
  /**
   * Indica si el mensaje es del usuario o del asistente IA
   */
  role: 'user' | 'assistant';
  /**
   * Texto simple del mensaje (para compatibilidad)
   */
  content?: string | null;
  /**
   * Mensaje completo del AI SDK con tool calls, parts, etc.
   */
  rawMessage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Referencias a documentos/recursos utilizados para generar la respuesta (solo para mensajes del asistente)
   */
  sources?:
    | {
        /**
         * Identificador del documento o recurso referenciado
         */
        resourceId?: string | null;
        /**
         * Título o nombre del documento referenciado
         */
        title?: string | null;
        /**
         * Fragmento del documento que fue relevante para la respuesta
         */
        excerpt?: string | null;
        /**
         * Puntuación de similitud del embedding (0-1)
         */
        relevanceScore?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Información adicional sobre el procesamiento del mensaje
   */
  metadata?: {
    /**
     * Número de tokens utilizados para generar este mensaje (solo para asistente)
     */
    tokens?: number | null;
    /**
     * Modelo de IA utilizado para generar la respuesta (ej: gpt-4)
     */
    model?: string | null;
    /**
     * Tiempo en milisegundos que tomó generar la respuesta
     */
    processingTime?: number | null;
    /**
     * Indica si se utilizó búsqueda RAG para generar esta respuesta
     */
    ragUsed?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestión de suscripciones de usuarios con Stripe
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  /**
   * Usuario propietario de la suscripción
   */
  user: string | User;
  /**
   * Identificador del plan de suscripción
   */
  planId: 'free' | 'basic' | 'pro';
  /**
   * Nombre del plan para mostrar al usuario
   */
  planName: string;
  /**
   * Estado actual de la suscripción
   */
  status: 'active' | 'inactive' | 'canceled' | 'past_due' | 'unpaid';
  /**
   * ID del customer en Stripe
   */
  stripeCustomerId?: string | null;
  /**
   * ID de la suscripción en Stripe (null para plan gratuito)
   */
  stripeSubscriptionId?: string | null;
  /**
   * ID del precio en Stripe
   */
  stripePriceId?: string | null;
  /**
   * Inicio del período actual de facturación
   */
  currentPeriodStart?: string | null;
  /**
   * Fin del período actual de facturación
   */
  currentPeriodEnd?: string | null;
  /**
   * Si la suscripción se cancelará al final del período
   */
  cancelAtPeriodEnd?: boolean | null;
  /**
   * Límites del plan actual
   */
  limits?: {
    /**
     * Límite de videos por mes (-1 = ilimitado)
     */
    videosPerMonth?: number | null;
    /**
     * Límite de mensajes de chat por mes (-1 = ilimitado)
     */
    messagesPerMonth?: number | null;
    /**
     * Límite de almacenamiento en GB
     */
    storageGB?: number | null;
  };
  /**
   * Uso actual del período de facturación
   */
  currentUsage?: {
    /**
     * Videos procesados en el período actual
     */
    videosProcessed?: number | null;
    /**
     * Mensajes de chat utilizados en el período actual
     */
    messagesUsed?: number | null;
    /**
     * Almacenamiento utilizado en GB
     */
    storageUsedGB?: number | null;
    /**
     * Última fecha de reset de contadores
     */
    lastResetDate?: string | null;
  };
  /**
   * Configuración para facturación por uso adicional (solo Pro)
   */
  variableBilling?: {
    /**
     * Habilitar facturación por uso adicional
     */
    enabled?: boolean | null;
    /**
     * Costo por video adicional procesado
     */
    extraVideosCost?: number | null;
    /**
     * Costo por GB adicional de almacenamiento
     */
    extraStorageCostPerGB?: number | null;
    /**
     * Cargos pendientes por uso adicional
     */
    pendingCharges?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'field-translations';
        value: string | FieldTranslation;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'pre-resources';
        value: string | PreResource;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: string | ApiKey;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  empresa?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  description?: T;
  mediaType?: T;
  pages?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  namespace?: T;
  lastUpdatedBy?: T;
  nombre_cliente?: T;
  caso?: T;
  tipo?: T;
  factura_suministros?:
    | T
    | {
        codigo_suministro?: T;
        periodo_consumo?:
          | T
          | {
              fecha_inicio?: T;
              fecha_fin?: T;
            };
        fecha_compra?: T;
        volumen_consumido?: T;
        unidad_medida?: T;
        proveedor_servicio?: T;
        codigo_factura?: T;
      };
  desplazamientos?:
    | T
    | {
        fecha_servicio?: T;
        empresa_servicio?: T;
        importe?: T;
        moneda?: T;
        cantidad_consumida?: T;
        unidad_medida?: T;
        tipo_combustible?: T;
        codigo_factura?: T;
      };
  materias_primas?:
    | T
    | {
        nombre_proveedor?: T;
        fecha_factura?: T;
        codigo_factura?: T;
        tipo_producto?: T;
        descripcion_producto?: T;
        peso_kg?: T;
        importe?: T;
        moneda?: T;
      };
  viajes_tipo_2?:
    | T
    | {
        fecha_viaje?: T;
        medio_transporte?: T;
        origen?: T;
        destino?: T;
        escalas?:
          | T
          | {
              escala?: T;
              id?: T;
            };
        numero_personas?: T;
        categoria_billete?: T;
        tipo_trayecto?: T;
        distancia?: T;
        fuente_distancia?: T;
        codigo_factura?: T;
      };
  variado_emails?:
    | T
    | {
        remitente?: T;
        fecha?: T;
        descripcion_consumo?: T;
        cantidad?: T;
        unidad_medida?: T;
      };
  consumos_combustible_tipo_1?:
    | T
    | {
        codigo_tarjeta_o_matricula?: T;
        fecha_repostaje?: T;
        cantidad_combustible?: T;
        unidad_medida?: T;
        tipo_combustible?: T;
        importe?: T;
        moneda?: T;
        codigo_factura?: T;
      };
  residuos?:
    | T
    | {
        codigo_recogida?: T;
        localizacion_recogida?: T;
        fecha_recogida?: T;
        tipo_residuo?: T;
        cantidad_residuo?: T;
        unidad_medida?: T;
      };
  viajes_tipo_1?:
    | T
    | {
        fecha_viaje?: T;
        medio_transporte?: T;
        origen?: T;
        destino?: T;
        escalas?:
          | T
          | {
              escala?: T;
              id?: T;
            };
        numero_personas?: T;
        categoria_billete?: T;
        tipo_trayecto?: T;
        distancia?: T;
        fuente_distancia?: T;
        codigo_factura?: T;
      };
  filters?: T;
  user_metadata?: T;
  extractedText?: T;
  description?: T;
  documentPages?:
    | T
    | {
        pageNumber?: T;
        extractedText?: T;
        summary?: T;
        id?: T;
      };
  chunks?:
    | T
    | {
        chunkIndex?: T;
        pageNumber?: T;
        content?: T;
        summary?: T;
        id?: T;
      };
  type?: T;
  file?: T;
  status?: T;
  progress?: T;
  logs?:
    | T
    | {
        step?: T;
        status?: T;
        at?: T;
        details?: T;
        data?: T;
        id?: T;
      };
  analyzeResult?: T;
  confidence?: T;
  processingMetadata?:
    | T
    | {
        pages?: T;
        textChunks?: T;
        vectorsGenerated?: T;
        jobIds?:
          | T
          | {
              jobId?: T;
              type?: T;
              id?: T;
            };
      };
  webhookUrl?: T;
  webhookSecret?: T;
  uploadedBy?: T;
  source?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-translations_select".
 */
export interface FieldTranslationsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  label?: T;
  isRequired?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  videos?: T;
  createdBy?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pre-resources_select".
 */
export interface PreResourcesSelect<T extends boolean = true> {
  project?: T;
  logs?:
    | T
    | {
        step?: T;
        status?: T;
        at?: T;
        details?: T;
        data?: T;
        id?: T;
      };
  user?: T;
  file?: T;
  status?: T;
  splitterResponse?:
    | T
    | {
        pages?:
          | T
          | {
              page?: T;
              id?: T;
            };
      };
  error?: T;
  derivedResourceIds?:
    | T
    | {
        resourceId?: T;
        id?: T;
      };
  lastUpdatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  name?: T;
  keyValue?: T;
  keyValueLastFour?: T;
  user?: T;
  projects?: T;
  hasAllProjects?: T;
  playgroundKey?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  title?: T;
  user?: T;
  isActive?: T;
  messageCount?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  role?: T;
  content?: T;
  rawMessage?: T;
  sources?:
    | T
    | {
        resourceId?: T;
        title?: T;
        excerpt?: T;
        relevanceScore?: T;
        id?: T;
      };
  metadata?:
    | T
    | {
        tokens?: T;
        model?: T;
        processingTime?: T;
        ragUsed?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  planId?: T;
  planName?: T;
  status?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  cancelAtPeriodEnd?: T;
  limits?:
    | T
    | {
        videosPerMonth?: T;
        messagesPerMonth?: T;
        storageGB?: T;
      };
  currentUsage?:
    | T
    | {
        videosProcessed?: T;
        messagesUsed?: T;
        storageUsedGB?: T;
        lastResetDate?: T;
      };
  variableBilling?:
    | T
    | {
        enabled?: T;
        extraVideosCost?: T;
        extraStorageCostPerGB?: T;
        pendingCharges?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ajustes generales del sitio: empresa, SEO, redes sociales y automatizaciones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion".
 */
export interface Configuracion {
  id: string;
  company: {
    name: string;
    shortName?: string | null;
    taxId?: string | null;
    email?: string | null;
    phone?: string | null;
    website?: string | null;
    address?: {
      street?: string | null;
      city?: string | null;
      province?: string | null;
      postalCode?: string | null;
      country?: string | null;
      extra?: string | null;
    };
  };
  brand?: {
    siteName?: string | null;
    siteDescription?: string | null;
    logo?: (string | null) | Media;
    favicon?: (string | null) | Media;
    defaultOgImage?: (string | null) | Media;
    themeColor?: string | null;
  };
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    keywords?: string | null;
    baseUrl?: string | null;
  };
  social?: {
    twitter?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    github?: string | null;
    telegram?: string | null;
    whatsapp?: string | null;
  };
  analytics?: {
    googleAnalyticsId?: string | null;
    metaPixelId?: string | null;
  };
  /**
   * Configuración para el sistema de evaluación de confianza de documentos
   */
  confidenceSettings?: {
    /**
     * Porcentaje mínimo de confianza requerido para que un campo se considere confiable (0-100)
     */
    confidenceThreshold?: number | null;
  };
  /**
   * Configura el webhook de N8n que se invoca al crear un Recurso.
   */
  automationEndpoint?: {
    enabled?: boolean | null;
    url?: string | null;
    httpMethod?: ('POST' | 'GET') | null;
    authType?: ('none' | 'bearer') | null;
    /**
     * Se enviará como Authorization: Bearer <token>
     */
    bearerToken?: string | null;
    sendResourceBody?: boolean | null;
    /**
     * Headers personalizados clave/valor
     */
    extraHeaders?:
      | {
          key?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Configuración del endpoint para dividir PDFs multi‑factura
   */
  splitter?: {
    url?: string | null;
    httpMethod?: 'POST' | null;
    /**
     * Si se deja vacío, reutilizar el Bearer del webhook de automatización si existe
     */
    bearerToken?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracion_select".
 */
export interface ConfiguracionSelect<T extends boolean = true> {
  company?:
    | T
    | {
        name?: T;
        shortName?: T;
        taxId?: T;
        email?: T;
        phone?: T;
        website?: T;
        address?:
          | T
          | {
              street?: T;
              city?: T;
              province?: T;
              postalCode?: T;
              country?: T;
              extra?: T;
            };
      };
  brand?:
    | T
    | {
        siteName?: T;
        siteDescription?: T;
        logo?: T;
        favicon?: T;
        defaultOgImage?: T;
        themeColor?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        keywords?: T;
        baseUrl?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        github?: T;
        telegram?: T;
        whatsapp?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        metaPixelId?: T;
      };
  confidenceSettings?:
    | T
    | {
        confidenceThreshold?: T;
      };
  automationEndpoint?:
    | T
    | {
        enabled?: T;
        url?: T;
        httpMethod?: T;
        authType?: T;
        bearerToken?: T;
        sendResourceBody?: T;
        extraHeaders?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
      };
  splitter?:
    | T
    | {
        url?: T;
        httpMethod?: T;
        bearerToken?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}